[package]
name = "bpwg"
version = "0.1.2"
authors = ["Frédéric van der Essen"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
zxcvbn = "2"
clap = { version = "3.1.6", features = ["derive"] }

