[package]
name = "gpwg"
version = "1.0.0"
authors = ["Frédéric van der Essen"]
edition = "2021"

[[bin]]
name = "gpwg"
test = false
bench = false

[dependencies]
rand = "0.8.0"
zxcvbn = "2"
clap = { version = "3.1.6", features = ["derive"] }
clipboard = "0.5.0"
ctrlc = "3.2.1"

